language: python

python:
  - "3.9.7"

install:
  - pip install --upgrade pip && pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql

before_script:
  - psql -c 'create database "test_db";' -U postgres


script:
  - nosetests --exe -v --with-coverage

after_success :
  - coveralls